final_app/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from . import views

app_name="final_app"

urlpatterns = [
    path('review/',views.review,name='review'),
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from final_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/',include('final_app.urls')),
]

final_app/models.py
from django.db import models
import numpy as np
from datetime import date
from datetime import datetime
from django.contrib.auth.models import User

class Industry(models.Model):
    industry_id = models.CharField(max_length=30,null=False)

def __str__(self):
    id = self.industry_id
    return (id)

RATING_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)

class Review(models.Model):
    industry_id = models.ForeignKey(Industry,on_delete=models.CASCADE)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField(default=datetime.now)
    user_name = models.CharField(max_length=200)
    comment = models.CharField(max_length=200,null=True)
    rating = models.IntegerField(choices=RATING_CHOICES)

final_app/forms.py
from django import forms
from django.forms import ModelForm,Textarea
from final_app.models import Industry,Review
from django.contrib.auth.models import User
from django.core.exceptions import NON_FIELD_ERRORS

#from reviews.models import UserProfileInfo
class IndustryForm(ModelForm):
    class meta:
        model = Industry
        fields = '__all__'


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        exclude = ('pub_date',)
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

final_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from final_app.models import Industry,Review
from final_app.forms import ReviewForm,IndustryForm
from final_app import forms
import numpy as np
from django.db.models import Count,Avg,Max
from django.db.models import IntegerField

def review(request):
    rate = Review.objects.all()
    if request.method == 'POST':
        f = ReviewForm(request.POST)
        review_details = Review.objects.order_by('pub_date')
        if f.is_valid():
            F=f.save(commit=False)
            try:
                obj1 = Review.objects.get(firstname = F.firstname, industry_id = F.industry_id)
                obj1.rating = F.rating
                obj1.pub_date = F.pub_date
                obj1.user_name = F.user_name
                obj1.comment = F.comment
                obj1.save()
            except:
                F.save()
        a = []
        industry_dict = Industry.objects.all()
        count = Industry.objects.all().count()
        for i in range(0,count):
            b = Review.objects.filter(industry_id=industry_dict[i]).aggregate(Avg('rating',output_field=IntegerField()))
            a.append(b)
        print(a)
        return render(request,'temp/rating.html',{'doc':industry_dict,'rating':a})
    else:
        f = ReviewForm()
        return render(request,'temp/review.html',{'form':f})

final_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
<h1>Review_page</h1>
  </head>
  <body>

  </body>
</html>

final_app/templates/temp/base.html
{% load staticfiles %}

<html>

  <head>
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <meta charset="utf-8">
    <title></title>
<h1>Review_page</h1>
  </head>
  <body>

    <div class = "container">
      <div class="jumbotron">

    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

             <form method="POST">
              {{form.as_p}}
              {% csrf_token %}

            </form>

          </div>
        </ul>
      </div>
    </div>

<div class="container">
           <div>
             <h1>Doctors</h1>
               {% if doctor_dict %}
           {% for x in doctor_dict %}
           <h2>{{x.uid}}</h2>
          </div>
          <div style="float:right;width:20%">
          <a class="btn" href="{% url 'final_app:review' %}">
          <button class="btn" type="submit">Review</button>
           </a>
         </div>
         {% endfor %}
         {% endif %}
<div>
  <div>
    <h1>Users</h1>
  {% if user_dict %}
  {% for x in user_dict %}

  <h2>{{x.uid}}</h2>
 </div>
 <div style="float:right;width:20%">

  </div>
{% endfor %}
{% endif %}

</div>
<!--
         {%if review_dict %}
         {% for x in review_dict %}
           <div style="float:center;width:20%"><h2>{{x.rating}}</h2>
           </div>
           {% endfor %}
           {% endif %}
-->
</div>
</div>
        </body>
</html>

final_app/templates/temp/rating.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <table>
      <div>
      {% if doc %}
      {% for doc in doc %}
        <tr>
          <th>{{doc.firstname}}</th>
        </tr>
  {% endfor %}
  {% endif %}
</div>
<div style="background-color:lightblue">
        <tr>
          {% if rating %}
          {% for i in rating %}
          <td>{{ i.rating__avg }}</td>
        </tr>
        {% endfor %}
      {% endif %}
    </div>
    </table>
  </body>
</html>

final_app/templates/temp/review.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>REVIEWS AND RATINGS</title>
  </head>
  <body>
<div class = "container" >

  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
  <input type="submit">
</form>

 </body>
</html>